default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  # database: db/development.sqlite3
  database: myapp_development_db

test:
  <<: *default
  # database: db/test.sqlite3
  database: myapp_test_db

production:
  <<: *default
  database: <%= ENV['YOUR_DATABASE'] %>
  user: <%= ENV['YOUR_DATABASE_USERNAME'] %> 
  password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>
